### ISSUE TITLE
Fix Integration Tests on SauceLabs

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-firefox#46]
It looks like the first-run page popping up on Firefox breaks testing on SauceLabs (but not locally). I think this is somehow breaking Selenium, but it is hard to say why. I am punting on this until later in the week since it is time to deploy.

![screen shot 2015-03-01 at 9 15 19 pm](https://cloud.githubusercontent.com/assets/64780/6435712/57a5e672-c058-11e4-8a24-ca4579015c25.png)

**Comment by hitesh96db** [comment]
For Jetpack, this happens locally as well sometimes. When the extension is loaded in the browser profile, the load reason sometimes happens to be `install` instead of the usual `startup`. When it's `install` the first run page opens up. I'm not sure why the profile changes.

**Comment by smcgregor** [comment]
Privly-Jetpack is replacing this old Xul version. See the new version nearing completion [here](https://github.com/privly/privly-jetpack).

(closing all outstanding issues on this repository since it is now deprecated)
