### ISSUE TITLE
Fix Integration Test Issue on Local Server for firefox_web

### ISSUE THREAD

**Issue by maniksingh92** [privly/privly-firefox#52]
* 4 out 11 tests for 'firefox_web' are failing on my machine.
* I installed all bundles and set up SQLite for my local web server. My server was responsive on localhost:3000 before I ran the integration tests
* I ran the ruby tests specific for firefox_web from ./privly-firefox/chrome/content/privly-applications/test/selenium.

Here is the prompt log:

You passed the arguments: {:platform=>"firefox_web", :release_status=>"experimental", :content_server=>"http://localhost:3000"}
Skipping due to release status: ZeroBin/new.html
Run options: 

# Running tests:

.....EE....

Finished tests in 180.214277s, 0.0610 tests/s, 0.0000 assertions/s.

  1) Error:
test_create_update_destroy(TestNew):
Selenium::WebDriver::Error::WebDriverError: unable to bind to locking port 7054 within 45 seconds
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:36:in `lock'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:17:in `locked'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver.rb:67:in `for'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `browser'
    /home/niko/privly/privly-firefox/chrome/content/privly-applications/test/selenium/specs/tc_new.rb:11:in `setup'

  2) Error:
test_create_update_destroy(TestNew):
Selenium::WebDriver::Error::WebDriverError: unable to bind to locking port 7054 within 45 seconds
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:36:in `lock'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:17:in `locked'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver.rb:67:in `for'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `browser'
    /home/niko/privly/privly-firefox/chrome/content/privly-applications/test/selenium/specs/tc_new.rb:78:in `teardown'

  3) Error:
test_creating_posts(TestNew):
Selenium::WebDriver::Error::WebDriverError: unable to bind to locking port 7054 within 45 seconds
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:36:in `lock'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:17:in `locked'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver.rb:67:in `for'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `browser'
    /home/niko/privly/privly-firefox/chrome/content/privly-applications/test/selenium/specs/tc_new.rb:11:in `setup'

  4) Error:
test_creating_posts(TestNew):
Selenium::WebDriver::Error::WebDriverError: unable to bind to locking port 7054 within 45 seconds
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:36:in `lock'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/socket_lock.rb:17:in `locked'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
    /var/lib/gems/1.9.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver.rb:67:in `for'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:13:in `browser'
    /home/niko/privly/privly-firefox/chrome/content/privly-applications/test/selenium/specs/tc_new.rb:78:in `teardown'

11 tests, 0 assertions, 0 failures, 4 errors, 0 skips

**Comment by smcgregor** [comment]
You opened this issue on the privly-firefox repository, but you are running tests for the privly-web repository. Which one is it?

**Comment by maniksingh92** [comment]
As you noted, I ran the tests from ./privly-web/public/apps/test/selenium . Still getting the same issue. I'll try to find fix for my situation and update it here

**Comment by maniksingh92** [comment]
@smcgregor I downgraded my firefox from v36 to v28. Now the selenium tests run perfectly. The issue seems to lie between selenium and Firefox 36.0.4. Is there any fix for this? Web search results show that many users are experiencing the same issue lately with v36.

**Comment by smcgregor** [comment]
Did you try updating selenium?

**Comment by maniksingh92** [comment]
I've updated to selenium 2.45 (latest) . And I ran the tests with firefox v28. Then I ran the tests with firefox v36. The tests are running fine now. But I get a new error, in both FF28 and FF36 -

 1) Error:
test_preview_button(TestHistory):
Capybara::ElementNotFound: Unable to find link or button "New Message"
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/node/actions.rb:13:in `click_link_or_button'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
    /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /home/niko/privly/privly-applications/test/selenium/specs/tc_history.rb:15:in `setup'

12 tests, 14 assertions, 0 failures, 1 errors, 0 skips

**Comment by smcgregor** [comment]
Things to try:

* Update to Ruby 1.9.3 and reinstall
* Set the "timeout" for capybara to more seconds and look at where it is hanging
* Build the HTML to make sure the expected element is present

**Comment by smcgregor** [comment]
Privly-Jetpack is replacing this old Xul version. See the new version nearing completion [here](https://github.com/privly/privly-jetpack).

(closing all outstanding issues on this repository since it is now deprecated)
